basePath: /
definitions:
  handlers.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handlers.LoginResponse:
    properties:
      access_token:
        type: string
      expires_in_h:
        type: integer
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API em Go com init-token, login e JWT
  title: API-Go Ultrasegura
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Valida init-token e usuário/senha, retorna access token
      parameters:
      - description: 'Init Token: Bearer <token>'
        in: header
        name: Authorization
        required: true
        type: string
      - description: Credenciais
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Login
      tags:
      - auth
  /token:
    get:
      description: Gera init-token via Basic Auth (agentId/agentSecret)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BasicAuth: []
      summary: Init Token
      tags:
      - auth
schemes:
- http
securityDefinitions:
  BasicAuth   Basic HTTP Authentication:
    type: basic
swagger: "2.0"
